### ISSUE TITLE
Not getting the embeds with sharing vault tools

### ISSUE THREAD

**Issue by Xverion** [BONNePlayground/VaultHuntersDiscordIntegrator#1]
### Expected behavior

As stated above it's not showing the vault tools in a embed. It just says xxx: [vault sword]

### Observed/Actual behavior

It showing people entering vaults in chat

### Steps/models to reproduce

install both mc2discord and latest vh

### VaultHunters version

latest vh version - 3.8.0-2176
latest mc2discord version - 3.3.0

**Comment by BONNe** [comment]
What version of this mod do you use?

**Comment by Xverion** [comment]
Sorry, should have included it but it was 1.1.1.

**Comment by BONNe** [comment]
Hmm, I am using it and it is working fine. Does your m2discord channel config contain `chat` messages?

Also, do you have any errors in the `logs/latest.log` when you share item in chat?

**Comment by Xverion** [comment]
nothing in latest log or debug log 

and channel config looks like this

`	[[Channels.Channel]]
		id = 123456789
		subscriptions = ["info", "chat", "command"]
		mode = "WEBHOOK"
`

**Comment by BONNe** [comment]
> nothing in latest log or debug log
> 
> and channel config looks like this
> 
> ` [[Channels.Channel]] id = 123456789 subscriptions = ["info", "chat", "command"] mode = "WEBHOOK" `

Have you edited any message layout in `[style]` section?

**Comment by Xverion** [comment]
Nothing at all. Everything is default apart from the ID's

**Comment by BONNe** [comment]
Do you have any extra mods, or non-default VH modpack configs?

**Comment by Xverion** [comment]
we added starlight - lightning improvements and lazy dfu

configs are the same

**Comment by BONNe** [comment]
Sorry for the late response. I did not have time to test this.

I set up the new server with this mc2discord channel configs:
```
	[[Channels.Channel]]
		id = 1
		subscriptions = ["info", "chat"]
		mode = "WEBHOOK"

	[[Channels.Channel]]
		id = 2
		subscriptions = ["info", "chat"]
		mode = "PLAIN_TEXT"

	[[Channels.Channel]]
		id = 3
		subscriptions = ["info", "chat"]
		mode = "EMBED"
```		

Then I started up the server and pasted the sword in-game.
I receive these 3 messages:
WEBHOOK:
![webhok](https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/assets/1344358/b91b2876-27fb-4a70-a4b3-15deee1c94ef)
PLAIN_TEXT:
![plain](https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/assets/1344358/fa4ad762-77b3-4887-9b25-8a580db32263)
EMBED
![embed](https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/assets/1344358/74087ddb-9788-479e-8321-f14ebe686ad3)

If you enable embed style, does it is displayed properly in Discord chat like this?
![embed_message](https://github.com/BONNePlayground/VaultHuntersDiscordIntegrator/assets/1344358/de042d5b-1834-43f7-b563-bbc46398e3b6)


If not then maybe your bot/channel has no option to create embeds.

**Comment by Xverion** [comment]
Apologies for the long delay on this. We found out that it was indeed a other mod causing the issues. FTBRanks to be specific.

**Comment by Xverion** [comment]
Let me know if you need anything else. I'll test as much as possible
