### ISSUE TITLE
Sharing Loot crashes Server

### ISSUE THREAD

**Issue by TheonlyTazz** [BONNePlayground/VaultHuntersDiscordIntegrator#9]
### Expected behavior

1. get Vault loot
2. open inventory
3. Ctrl-T
4. Show Stats in discord

### Observed/Actual behavior

4 - Crash

### Steps/models to reproduce

see above

### VaultHunters version

VH 3.15.1.3 
DiscordIntegrator 1.5.3
Mc2Discord 4.2.4 using Webhooks

### Other

Crashlog:
https://gist.github.com/TheonlyTazz/ab50a06d3a405f69759b8eb110a2b808

**Comment by BONNe** [comment]
Please update to VaultHuntersDiscordIntegration-1.5.4-1.18.2

https://www.curseforge.com/minecraft/mc-mods/vaulthunters-dc-bot-connector/files/5601631

When VH updates, they sometimes change stuff that breaks this mod. So when the update comes out, it most likely address the compatibility.

**Comment by TheonlyTazz** [comment]
thanks, i didn't notice there being a new version! this fixed it!
